package:
    name: toolz
    version: "0.10.0"

build:
    number: {{environ.get('BINSTAR_BUILD', 1)}}

requirements:
    build:
      - setuptools
      - python

    run:
      - python

test:
    requires:
      - pytest
    imports:
      - toolz
    commands:
      - py.test -x --doctest-modules --pyargs toolz

about:
    home: https://toolz.readthedocs.io/
    license: BSD
